[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "D9FW4DHWSVcRDX4CUSDm4q6B5AGoMEenrtyetwLYkMzJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
